[project]
name = "api-jornada"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy>=2.0.36",
]

[tool.poetry.scripts]
main = "src.main:main"
